version: 2.1
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.8
      - image: cimg/postgres:14.6
        environment:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres      
    steps:
      - checkout
      - run:
          name: Setup Virtual Env
          command: |
            python3 -m venv project_env
            echo "source ./project_env/bin/activate" >> $BASH_ENV
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Wait for Postgres to start
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Test
          command: pytest
  deploy:
    docker:
      - image: cimg/python:3.8
      - image: cimg/postgres:14.6
        environment:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres      
    steps:
       - run:
          name: AWS EC2 deploy
          command: | 
            ssh -o StrictHostKeyChecking=no ubuntu@52.91.121.252  \
            "echo Start deploy && \
            cd ~/Demo && \
            git pull && \
            pip install -r requirements.txt && \
            python3 -m uvicorn app.main:app && \
            echo Deploy end"

workflows:
  build-test-and-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main


